# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d5c3253ae0f5c96ce2c056bc89c83af4b00eec50a8956fdec90341f45be98a5e74a1467036be64ba07d567b555a9cb8877bab85ba131e0d9ce29ded4b5ce0e9

test:
  secret_key_base: 279b82f15ae62f843269189b1b7c53d8f7179429c8a960ecf27906443ec1bac09a6667cf14744a7db3289489302ab80a9e0460cac58089a1017fb98a83de0807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
